<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Brand;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $brand = array("Gucci",
"Louis Vuitton",
"Prada",
"Chanel",
"Hermès",
"Dior",
"Balenciaga",
"Versace",
"Givenchy",
"Burberry",
"Fendi",
"Saint Laurent",
"Tom Ford",
"Alexander McQueen",
"Valentino",
"Dolce & Gabbana",
"Celine",
"Bottega Veneta",
"Off-White",
"Supreme",
"Nike",
"Adidas",
"Puma",
"Vans",
"New Balance",
"Under Armour",
"Reebok",
"Champion",
"Fila",
"Converse",
"Levi's",
"Wrangler",
"Calvin Klein",
"Tommy Hilfiger",
"Ralph Lauren",
"Lacoste",
"Hugo Boss",
"Armani",
"Diesel",
"Guess",
"H&M",
"Zara",
"Uniqlo",
"ASOS",
"Mango",
"Topshop",
"Forever 21",
"Urban Outfitters",
"Bershka",
"Stradivarius",
"Massimo Dutti",
"Pull & Bear",
"River Island",
"Primark",
"Express",
"GAP",
"Old Navy",
"Abercrombie & Fitch",
"Hollister",
"American Eagle",
"Aéropostale",
"J.Crew",
"Banana Republic",
"Madewell",
"Victoria's Secret",
"Pink",
"Lululemon",
"The North Face",
"Patagonia",
"Columbia",
"Arc'teryx",
"Fjällräven",
"Moncler",
"Canada Goose",
"Rains",
"Everlane",
"Reformation",
"Stella McCartney",
"Allbirds",
"Veja",
"People Tree",
"Outerknown",
"Thought Clothing",
"Eileen Fisher",
"Cotopaxi",
"Levi's Vintage Clothing",
"Nudie Jeans",
"G-Star RAW",
"Carhartt WIP",
"Dickies",
"Rag & Bone",
"Frame",
"Balmain",
"Kenzo",
"Thom Browne",
"Maison Margiela",
"ACNE Studios",
"Comme des Garçons",
"Isabel Marant",
"Ganni");
        for($i=0;$i<100;$i++){
            Brand::create([
                'brand_name' => $brand[$i],
            ]);
        }
    }
}
