<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Category;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $category = array(
            'T-Shirts',
            'Blouses',
            'Shirts',
            'Tank Tops',
            'Sweaters',
            'Hoodies',
            'Sweatshirts',
            'Crop Tops',
            'Tunics',
            'Polo Shirts',
            'Henleys',
            'Jeans',
            'Pants/Trousers',
            'Shorts',
            'Leggings',
            'Skirts',
            'Capris',
            'Joggers',
            'Cargo Pants',
            'Chinos',
            'Maxi Dresses',
            'Midi Dresses',
            'Mini Dresses',
            'Cocktail Dresses',
            'Evening Gowns',
            'Sundresses',
            'Shift Dresses',
            'Wrap Dresses',
            'Shirt Dresses',
            'Bodycon Dresses',
            'Jackets',
            'Coats',
            'Blazers',
            'Vests',
            'Parkas',
            'Trench Coats',
            'Windbreakers',
            'Raincoats',
            'Bomber Jackets',
            'Peacoats',
            'Bras',
            'Panties',
            'Boxers',
            'Briefs',
            'Boxer Briefs',
            'Thongs',
            'Camisoles',
            'Slips',
            'Shapewear',
            'Lingerie',
            'Yoga Pants',
            'Sports Bras',
            'Athletic Shorts',
            'Workout Tops',
            'Tracksuits',
            'Running Tights',
            'Compression Wear',
            'Sports Jackets',
            'Athletic Socks',
            'Base Layers',
            'Pajamas',
            'Nightgowns',
            'Robes',
            'Sleep Shirts',
            'Nightshirts',
            'Loungewear',
            'Suits',
            'Tuxedos',
            'Dress Shirts',
            'Evening Gowns',
            'Blazers',
            'Dress Pants',
            'Ties/Bow Ties',
            'Formal Vests',
            'Waistcoats',
            'Cocktail Dresses',
            'Bikinis',
            'One-Piece Swimsuits',
            'Swim Trunks',
            'Board Shorts',
            'Rash Guards',
            'Swim Dresses',
            'Cover-Ups',
            'Scarves',
            'Gloves',
            'Hats',
            'Belts',
            'Ties',
            'Sunglasses',
            'Watches',
            'Handbags',
            'Backpacks',
            'Socks',
            'Sneakers',
            'Boots',
            'Sandals',
            'Heels',
            'Flats',
            'Loafers',
            'Oxfords',
            'Slippers',
            'Espadrilles',
            'Flip-Flops',
            'Winter Coats',
            'Snow Pants',
            'Thermals',
            'Ski Jackets',
            'Summer Dresses',
            'Beachwear',
            'Rain Boots',
            'Sarees',
            'Kurtas/Kurtis',
            'Kimono',
            'Hanbok',
            'Kilt',
            'Dirndl',
            'Dashiki',
            'Jilbab/Abaya',
            'Cheongsam/Qipao',
            'Poncho',
            'Maternity Dresses',
            'Maternity Tops',
            'Maternity Pants',
            'Nursing Bras',
            'Maternity Leggings',
            'Maternity Skirts',
            'Dress Shirts',
            'Pencil Skirts',
            'Blazers',
            'Slacks',
            'Work Dresses',
            'Suit Jackets',
            'Work Boots',
            'Uniforms',
            'Sequin Dresses',
            'Cocktail Dresses',
            'Club Dresses',
            'Bodycon Skirts',
            'Party Tops',
            'Statement Jumpsuits',
            'Plus Size Clothing',
            'Petite Clothing',
            'Tall Clothing',
            'Adaptive Clothing',
            'Modest Clothing',
            'Retro Dresses',
            'Vintage T-Shirts',
            'High-Waisted Jeans',
            'Flapper Dresses',
            'Rockabilly Clothing',
            'Halloween Costumes',
            'Cosplay Outfits',
            'Themed Party Costumes',
            'Historical Costumes',
            'Kaftans',
            'Sarongs',
            'Beach Dresses',
            'Resort Wear Pants',
            'Linen Shirts'
        );
        
        for($i=0;$i<sizeof($category);$i++){
            Category::create([
                'category_name' => $category[$i],
            ]);
        }
        
    }
}
